### ISSUE TITLE
zsh is a dependancy

### ISSUE THREAD

**Issue by the4ndy** [aforemny/googl#2]
I tried installing this on a default Xubuntu 16.04 install and I lack zsh and thus the script does not run at all.....can the script be run with bash instead?

**Comment by AchoArnold** [comment]
Hey @the4ndy

The script can run with bash with no problems. I've tested it extensively on bash. Also, if you prefer the GUI version or if you need some documentation, you can checkout https://github.com/AchoArnold/googl

Thanks
